const db = [
  {
    code: 'bch',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0.02169939,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 15,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 3,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'bond',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'amp',
    name: '',
    usd: 0,
    amount: {
      coinbase: 35.2356807,
      kraken: 0,
      gemini: 125.37760765,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 10,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 3,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'celo',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0.96080522,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 6,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'cvc',
    name: '',
    usd: 0,
    amount: {
      coinbase: 15.63931389,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'dnt',
    name: '',
    usd: 0,
    amount: {
      coinbase: 29.69072611,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'gusd',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 130.52890408,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 130,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'lrc',
    name: '',
    usd: 0,
    amount: {
      coinbase: 16.3053424,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 8 + 4,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'nkn',
    name: '',
    usd: 0,
    amount: {
      coinbase: 11.06811621,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'nu',
    name: '',
    usd: 0,
    amount: {
      coinbase: 24.53375912,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'oxt',
    name: '',
    usd: 0,
    amount: {
      coinbase: 13.74786028,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 4 + 8,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'paxg',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0.00003441,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'ren',
    name: '',
    usd: 0,
    amount: {
      coinbase: 9.94362702,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'sand',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 17.313937,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 5,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'skl',
    name: '',
    usd: 0,
    amount: {
      coinbase: 14.62985334,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'pax',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 100.40684914,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 100,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'usdc',
    name: '',
    usd: 0,
    amount: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 1000.61027380,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 150 + 850,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'dai',
    name: '',
    usd: 0,
    amount: {
      coinbase: 8.9866296,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 2076.02418796,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 2000 + 100,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'busd',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 100.40684914,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 100,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'ada',
    name: '',
    usd: 0,
    amount: {
      coinbase: 6.689929,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'algo',
    name: '',
    usd: 0,
    amount: {
      coinbase: 6.772413,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'ankr',
    name: '',
    usd: 0,
    amount: {
      coinbase: 56.91090033,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'atom',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0.439706,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'bat',
    name: '',
    usd: 0,
    amount: {
      coinbase: 7.03150912,
      kraken: 0,
      gemini: 6.55297694,
      cake: 0,
      blockfi: 0,
      brave: 1,
    },
    investment: {
      coinbase: 10,
      kraken: 0,
      gemini: 5,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'btc',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0.00554980,
      brave: 0,
    },
    investment: {
      coinbase: 150,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 65,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'comp',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0.01802347,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'dfi',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 20.68071,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 60,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'doge',
    name: '',
    usd: 0,
    amount: {
      coinbase: 257.9566093,
      kraken: 0,
      gemini: 0,
      cake: 191.08572,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 100 + 50,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'eth',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0.04321526,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 50 + 60,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'fil',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'zec',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'grt',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'link',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 2.25361672,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 100,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'ltc',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0.31046849,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 50 + 60,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'matic',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'mkr',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'xlm',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'xmr',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'xtz',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'eos',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'kava',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'dot',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'uni',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  {
    code: 'forth',
    name: '',
    usd: 0,
    amount: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
  //---------------------------
  {
    code: 'gtc',
    name: '',
    usd: 5.89,
    amount: {
      coinbase: 1.28516119,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    investment: {
      coinbase: 15,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
    earnInvestment: {
      coinbase: 0,
      kraken: 0,
      gemini: 0,
      cake: 0,
      blockfi: 0,
      brave: 0,
    },
  },
];

let cryptoDB = {};
db.forEach(item => {
  let a = item.amount;
  let i = item.investment;
  let e = item.earnInvestment;
  cryptoDB[item.code.toUpperCase()] = {
    amount: (a.coinbase + a.kraken + a.gemini + a.cake + a.blockfi + a.brave).toFixed(4),
    investment: (i.coinbase + i.kraken + i.gemini + i.cake + i.blockfi + i.brave).toFixed(2),
    earn: (e.coinbase + e.kraken + e.gemini + e.cake + e.blockfi + e.brave).toFixed(2),
  }
});

export default cryptoDB;